# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


ignored = ["test", "appengine"]

[prune]
  non-go = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  # version = "v0.2.0"
  revision = "a368813c5e648fee92e5f6c30e3944ff9d5e8895"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  # version = "1.0.4"
  # 1.0.4 has a race condition on panic in logrous hooks taht is triggere by our test suite
  revision = "8c0189d9f6bbf301e5d055d34268156b317016af"

[[constraint]]
  branch = "master"
  name = "github.com/ayufan/golang-kardianos-service"

# temporary fork to handle Sirupsen -> sirupsen
[[constraint]]
  name = "github.com/docker/distribution"
  branch = "gitlab-runner"
  source = "github.com/nolith/docker-distribution"

# temporary fork to handle Sirupsen -> sirupsen
[[constraint]]
  name = "github.com/docker/docker"
  branch = "gitlab-runner"
  source = "github.com/nolith/moby"

[[constraint]]
  name = "github.com/docker/go-connections"
  version = "0.3.0"

[[constraint]]
  name = "github.com/docker/machine"
  # version = "0.13.0"
  revision = "7b7a141da84480342357c51838be142bf183b095"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  revision = "dffeb57df75d6a911f00232155194e43d79d38d7"

[[constraint]]
  name = "github.com/golang/mock"
  revision = "06883d979f10cc178f2716846215c8cf90f9e363"

[[constraint]]
  name = "github.com/gorhill/cronexpr"
  revision = "f0984319b44273e83de132089ae42b1810f4933b"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  revision = "03c5bf6be031b6dd45afec16b1cf94fc8938bc77"

[[constraint]]
  name = "github.com/jpillora/backoff"
  revision = "06c7a16c845dc8e0bf575fafeeca0f5462f5eb4d"

[[constraint]]
  name = "github.com/kardianos/osext"
  revision = "c2c54e542fb797ad986b31721e1baedf214ca413"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "3.0.3"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  # version = "0.8.0"
  revision = "334af0119a8f8fb6af5bb950d535c482cac7f836"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "b1f989447a57594c728884458a39abf3a73447f7"

[[constraint]]
  # branch = "master"
  name = "github.com/tevino/abool"
  revision = "3c25f2fe7cd0ef3eabefce1d90efd69a65d35b12"

[[constraint]]
  name = "github.com/urfave/cli"
  revision = "cfb38830724cc34fedffe9a2a29fb54fa9169cd1"

[[constraint]]
  branch = "master"
  name = "gitlab.com/ayufan/golang-cli-helpers"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "1f22c0103821b9390939b6776727195525381532"

[[constraint]]
  name = "golang.org/x/net"
  revision = "f2499483f923065a842d38eb4c7f1927e6fc6e6d"

[[constraint]]
  # branch = "v2"
  name = "gopkg.in/yaml.v2"
  revision = "e4d366fc3c7938e2958e662b4258c7a89e1f0e3e"

[[constraint]]
  name = "k8s.io/kubernetes"
  # version = "1.3.5"
  revision = "b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5"

[[constraint]]
  name = "github.com/mattn/go-zglob"
  branch = "master"


##
## Refrain innovations ;)
##

[[override]]
  name = "cloud.google.com/go"
  revision = "05253f6a829103296c351b643f6815aedd81a3fb"

[[override]]
  name = "github.com/Azure/go-ansiterm"
  revision = "19f72df4d05d31cbe1c56bfc8045c96babff6c7e"

[[override]]
  name = "github.com/Microsoft/go-winio"
  revision = "ce2922f643c8fd76b46cadc7f404a06282678b34"

[[override]]
  name = "github.com/blang/semver"
  version = "v3.3.0"

[[override]]
  name = "github.com/coreos/go-oidc"
  revision = "1efe0e1303a62da553fcb6beb8bd2aa9250c0ca8"

[[override]]
  name = "github.com/docker/docker-credential-helpers"
  revision = "b7c53e02cd1a9a01500a58f22d83c6e964bc59db"

[[override]]
  name = "github.com/docker/engine-api"
  revision = "4290f40c056686fcaa5c9caf02eac1dde9315adf"

[[override]]
  name = "github.com/docker/go-units"
  revision = "eb879ae3e2b84e2a142af415b679ddeda47ec71c"

[[override]]
  name = "github.com/docker/spdystream"
  revision = "449fdfce4d962303d702fec724ef0ad181c92528"

[[override]]
  name = "github.com/emicklei/go-restful"
  revision = "89ef8af493ab468a45a42bb0d89a06fccdd2fb22"

[[override]]
  name = "github.com/ghodss/yaml"
  revision = "aa0c862057666179de291b67d9f093d12b5a8473"

[[override]]
  name = "github.com/go-ini/ini"
  revision = "20b96f641a5ea98f2f8619ff4f3e061cff4833bd"

[[override]]
  name = "github.com/gogo/protobuf"
  revision = "f20a1444730c7d9949b880a0309e737d007def25"

[[override]]
  name = "github.com/golang/protobuf"
  revision = "f592bd283e9ef86337a432eb50e592278c3d534d"

[[override]]
  name = "github.com/google/cadvisor"
  revision = "2ed7198f77395ee9a172878a0a7ab92ab59a2cfd"

[[override]]
  name = "github.com/google/gofuzz"
  revision = "fd52762d25a41827db7ef64c43756fd4b9f7e382"

[[override]]
  name = "github.com/gorilla/context"
  revision = "08b5f424b9271eedf6f9f0ce86cb9396ed337a42"

[[override]]
  name = "github.com/gorilla/mux"
  revision = "599cba5e7b6137d46ddf58fb1765f5d928e69604"

[[override]]
  name = "github.com/imdario/mergo"
  revision = "50d4dbd4eb0e84778abe37cefef140271d96fade"

[[override]]
  name = "github.com/jonboulle/clockwork"
  revision = "e3653ace2d63753697e0e5b07b9393971c0bba9d"

[[override]]
  name = "github.com/juju/ratelimit"
  revision = "77ed1c8a01217656d2080ad51981f6e99adaa177"

[[override]]
  name = "github.com/minio/go-homedir"
  revision = "4d76aabb80b22bad8695d3904e943f1fb5e6199f"

# temporary fork to hanled Sirupsen -> sirupsen
[[override]]
  name = "github.com/opencontainers/runc"
  branch = "gitlab-runner"
  source = "github.com/nolith/runc"

[[override]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "313f40bdfcc04c6b0f7b8a8c3e91a7b7a3a0ef4e"

[[override]]
  name = "github.com/pborman/uuid"
  revision = "c55201b036063326c5b1b89ccfe45a184973d073"

[[override]]
  name = "github.com/prometheus/procfs"
  revision = "abf152e5f3e97f2fafac028d2cc06c1feb87ffa5"

[[override]]
  name = "github.com/spf13/pflag"
  revision = "4f9190456aed1c2113ca51ea9b89219747458dc1"

[[override]]
  name = "github.com/stretchr/objx"
  revision = "cbeaeb16a013161a98496fad62933b1d21786672"

[[override]]
  name = "github.com/ugorji/go"
  revision = "4a1cb5252a6951f715a85d0e4be334c2a2dbf2a2"

[[override]]
  name = "github.com/vbatts/tar-split"
  revision = "e4899282720706fae5fde9dc1ee80bc3fefe10c2"

[[override]]
  name = "golang.org/x/oauth2"
  revision = "3b966c7f301c0c71c53d94dc632a62df0a682cd7"

[[override]]
  name = "golang.org/x/sys"
  revision = "042a8f53ce82bbe081222da955159491e32146a0"

[[override]]
  name = "google.golang.org/appengine"
  revision = "e951d3868b377b14f4e60efa3a301532ee3c1ebf"
