trigger runner-incept tests:
  extends:
  - .rules:merge_request_pipelines:no_docs
  stage: integration
  trigger: gitlab-org/ci-cd/tests/runner-incept
  needs:
  - 'binaries linux/386 linux/amd64 linux/arm linux/arm64 linux/s390x linux/ppc64le'
